{% set version = "0.0.1" %}
{% set sha256 = "ad76998cf6db0d76f8b3326f085d6b8c01f57302b5d89fd057669b6390df978f" %}
{% set revision= "bd5816d7c0406805fc14a0de56b54df15f4114d8" %}

package:
  name: super_sptree
  version: {{ version }}

source:
  git_url: https://github.com/leomrtns/super_sptree
  git_rev: {{ revision }}
  #  url: https://github.com/leomrtns/super_sptree/archive/v{{version}}.tar.gz 
  #  sha256: '{{sha256}}'
  md5: unused

extra:
  skip-lints:
    - uses_git_url

build:
  number: 3
  skip: true # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - libcxx 4.0.*  # [osx]
    - openmp 4.0.*  # [osx]
  host:
    - zlib
    - libcxx 4.0.*  # [osx]
    - openmp 4.0.*  # [osx]

  run:
    - zlib

test:
  commands:
    - super_sptree --help 

about:
  home: https://github.com/leomrtns/super_sptree 
  license: "GPL-3"
  summary: "algorithms for supertree estimation"
  identifiers:
    - biotools:super_sptree
    - doi:xx

