language: c
git:
  submodules: true
#install: make get-deps  # 
compiler:
  - gcc
before_install:
  - export OMP_NUM_THREADS=4 
  - sudo apt-get update
  - sudo apt-get install -y check 

# the Default script is "./configure && make && make test"

